import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  ArrowLeft,
  Bookmark,
  Download,
  Copy,
  Check,
  RotateCcw,
  BookOpen,
  FileCheck2,
  Globe2,
  Clock,
  Layers
} from 'lucide-react';
import { Button } from '../../components/common/Button';
import { VerdictCard } from '../../components/verification/VerdictCard';
import { EvidenceCardList } from '../../components/verification/EvidenceCard';
import { SourceCardList } from '../../components/verification/SourceCard';
import { EvidenceTimeline } from '../../components/verification/EvidenceTimeline';
import { verificationApi } from '../../api/verification.api';
import type { VerificationResult } from '../../types';

export const ResultsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [result, setResult] = useState<VerificationResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const load = async () => {
      if (!id) return;
      try {
        const data = await verificationApi.getVerificationById(id);
        setResult(data);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [id]);

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    if (!result) return;
    const reportText = `==============================\nTRUTHWEAVE VERIFICATION REPORT\n==============================\nID: ${result.id}\nDate: ${new Date(result.createdAt).toLocaleString()}\nVerdict: ${result.verdict}\nConfidence: ${result.confidence}%\n\nCLAIM:\n${result.claim}\n\nSUMMARY:\n${result.summary}\n\nAI EXPLANATION:\n${result.explanation}\n\nEVIDENCE COUNT: ${result.evidence.length}\nSOURCES COUNT: ${result.sources.length}\n==============================\nGenerated by TruthWeave (https://truthweave.ai)`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `truthweave_report_${result.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <div className="flex flex-col items-center gap-3">
          <div className="h-10 w-10 animate-spin rounded-full border-2 border-sky-400 border-t-transparent" />
          <span className="text-sm font-medium text-slate-400">Loading verification report...</span>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="text-center py-20 space-y-4">
        <h3 className="text-lg font-bold text-white">Verification Report Not Found</h3>
        <p className="text-xs text-slate-400">The requested verification record could not be retrieved.</p>
        <Button variant="primary" onClick={() => navigate('/verify')}>
          Start New Verification
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-5xl mx-auto pb-12 animate-in fade-in duration-300">
      {/* Top Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 pb-4 border-b border-slate-800/80">
        <button
          onClick={() => navigate('/dashboard')}
          className="flex items-center gap-2 rounded-xl border border-slate-800 bg-slate-900/60 px-3 py-1.5 text-xs font-semibold text-slate-300 hover:bg-slate-800 hover:text-white transition-all"
        >
          <ArrowLeft size={14} />
          <span>Back to Dashboard</span>
        </button>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="secondary"
            size="sm"
            onClick={handleCopyLink}
            icon={copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
          >
            {copied ? 'Link Copied' : 'Share'}
          </Button>

          <Button
            variant="secondary"
            size="sm"
            onClick={() => setSaved(!saved)}
            icon={<Bookmark size={14} className={saved ? 'text-sky-400 fill-sky-400' : ''} />}
          >
            {saved ? 'Saved' : 'Save Result'}
          </Button>

          <Button
            variant="secondary"
            size="sm"
            onClick={handleExport}
            icon={<Download size={14} />}
          >
            Export Report
          </Button>

          <Button
            variant="gradient"
            size="sm"
            onClick={() => navigate('/verify')}
            icon={<RotateCcw size={14} />}
          >
            Verify Another
          </Button>
        </div>
      </div>

      {/* Primary Large Verdict Card */}
      <VerdictCard result={result} />

      {/* Media / Forensic Preview if applicable */}
      {result.mediaPreviewUrl && (
        <div className="rounded-3xl border border-slate-800 bg-slate-900/40 p-6 backdrop-blur-xl">
          <h3 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
            <Layers size={16} className="text-sky-400" />
            <span>Forensic Media Inspector</span>
          </h3>
          <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950/80 p-2">
            <img
              src={result.mediaPreviewUrl}
              alt="Forensics preview"
              className="max-h-96 w-full rounded-xl object-contain"
            />
          </div>
          <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-400">
            <span>Dimensions: {result.dimensions || '3840 x 2160'}</span>
            <span>Format: {result.fileType || 'image/jpeg'}</span>
            <span className="font-mono text-rose-400">Diffusion Artifact Score: 0.94</span>
          </div>
        </div>
      )}

      {/* Detailed AI Explanation Section */}
      <div className="rounded-3xl border border-slate-800 bg-slate-900/40 p-6 sm:p-8 backdrop-blur-xl space-y-3">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-sky-400 font-mono">
          <BookOpen size={15} />
          <span>Detailed AI Reasoning & Evaluation</span>
        </div>
        <h3 className="text-lg font-bold text-white tracking-tight">
          How TruthWeave Formed This Verdict
        </h3>
        <p className="text-sm text-slate-300 leading-relaxed">
          {result.explanation}
        </p>
      </div>

      {/* Evidence Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileCheck2 size={18} className="text-sky-400" />
            <h3 className="text-lg font-bold text-white tracking-tight">
              Evidence Breakdown ({result.evidence.length})
            </h3>
          </div>
          <span className="text-xs text-slate-500">Cross-verified facts & claims</span>
        </div>

        <EvidenceCardList evidence={result.evidence} />
      </div>

      {/* Sources Section */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Globe2 size={18} className="text-sky-400" />
            <h3 className="text-lg font-bold text-white tracking-tight">
              Authoritative Sources & Registries ({result.sources.length})
            </h3>
          </div>
          <span className="text-xs text-slate-500">Peer-reviewed & government publishers</span>
        </div>

        <SourceCardList sources={result.sources} />
      </div>

      {/* Evidence Timeline Section */}
      <div className="rounded-3xl border border-slate-800 bg-slate-900/40 p-6 sm:p-8 backdrop-blur-xl space-y-4">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-sky-400 font-mono">
          <Clock size={15} />
          <span>Forensic Pipeline Sequence</span>
        </div>
        <h3 className="text-lg font-bold text-white tracking-tight mb-4">
          Verification Step-by-Step Timeline
        </h3>

        <EvidenceTimeline timeline={result.timeline} />
      </div>
    </div>
  );
};
